config/routes.rb
Rails.application.routes.draw do
  resources :emp_leave_masters
  resources :emp_requests
  resources :emp_masters
  resources :health_masters
  resources :emp_healths
  resources :roles_masters
  resources :leave_types
  resources :roles_masters
  resources :leave_types 
  devise_for :users
  get 'home/index'

  
   root 'home#index'

 devise_scope :user do 
     get '/users/sign_up' => 'users#sign_in'
  end

  get '/users' => 'users#index'

  get '/users/new' => 'users#new', :as => 'new_user'
  get '/users/:id/edit' => 'users#edit', :as => 'user_edit'
  get '/users/:id' => 'users#show', :as => 'user'
  patch '/users/:id' => 'users#update', :as => 'update_user'

  get '/users/create' => 'users#create', as: :create_user
  post 'create_users' => 'users#create', as: :create_users

end

app/models/roles_master.rb
class RolesMaster < ActiveRecord::Base
 validates :role_name, presence: {message: "Role name cannot be blank"}
 validates :description, presence: {message: "Description cannot be blank"}
end

app/controllers/roles_masters_controller.rb
class RolesMastersController < ApplicationController
  before_action :set_roles_master, only: [:show, :edit, :update, :destroy]
load_and_authorize_resource
 
  # GET /roles_masters
  # GET /roles_masters.json
  def index
    @roles_masters = RolesMaster.all
  end

  # GET /roles_masters/1
  # GET /roles_masters/1.json
  def show
  end

  # GET /roles_masters/new
  def new
    @roles_master = RolesMaster.new
  end

  # GET /roles_masters/1/edit
  def edit
  end

  # POST /roles_masters
  # POST /roles_masters.json
  def create
    @roles_master = RolesMaster.new(roles_master_params)

    respond_to do |format|
      if @roles_master.save
        format.html { redirect_to @roles_master, notice: 'Roles master was successfully created.' }
        format.json { render :show, status: :created, location: @roles_master }
      else
        format.html { render :new }
        format.json { render json: @roles_master.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles_masters/1
  # PATCH/PUT /roles_masters/1.json
  def update
    respond_to do |format|
      if @roles_master.update(roles_master_params)
        format.html { redirect_to @roles_master, notice: 'Roles master was successfully updated.' }
        format.json { render :show, status: :ok, location: @roles_master }
      else
        format.html { render :edit }
        format.json { render json: @roles_master.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles_masters/1
  # DELETE /roles_masters/1.json
  def destroy
    @roles_master.destroy
    respond_to do |format|
      format.html { redirect_to roles_masters_url, notice: 'Roles master was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_roles_master
      @roles_master = RolesMaster.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def roles_master_params
      params.require(:roles_master).permit(:role_name, :description, :status)
    end
end

app/helpers/roles_masters_helper.rb
module RolesMastersHelper
end

app/views/roles_masters/_form.html.erb
<%= simple_form_for(@roles_master) do |f| %>
  <%= f.error_notification %>

<legend>New User Account</legend>
 <div class="container">
  
    <div class="form-horizontal">
      <div class="form-group">
        <div class="col-md-3">
            <%= f.input :role_name,class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-md-3">
          <%= f.input :description,class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-md-3">
         	<%= f.input :status %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-md-1">
          <%= f.button :submit,"Submit",class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/roles_masters/edit.html.erb
<br/>
<br/>
<br/>
<body>
<h1>Editing Roles Master</h1>
<div class="container">
	   <div class="row">
	      <div class="col-md-4 col-xs-4"></div>
	      <div class="col-md-4 col-xs-4"> <%= render 'form' %></div>
	      <div class="col-md-4 col-xs-4"></div>
		</div>
		<div class="row">
		<br/>
			<div class="col-md-4 col-xs-4"></div>
			<div class="col-md-4 col-xs-4">
				<%= link_to 'Show', @roles_master %> |
<%= link_to 'Back', roles_masters_path %>
</div>
			<div class="col-md-4 col-xs-4"></div>
		</div>
  	</div>
</body>
</html>

app/views/roles_masters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Roles Masters</h1>

<table class="table">
  <thead>
    <tr>
      <th>Role name</th>
      <th>Description</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @roles_masters.each do |roles_master| %>
      <tr>
        <td><%= roles_master.role_name %></td>
        <td><%= roles_master.description %></td>
        <td><%= roles_master.status %></td>
        <td><%= link_to 'Show', roles_master %></td>
        <td><%= link_to 'Edit', edit_roles_master_path(roles_master) %></td>
        <td><%= link_to 'Destroy', roles_master, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Roles master', new_roles_master_path %>

app/views/roles_masters/new.html.erb
<br/>
<br/>
<br/>
<body>
<h1>New Roles Master</h1>
	<div class="container">
	   <div class="row">
	      <div class="col-md-4 col-xs-4"></div>
	      <div class="col-md-4 col-xs-4"> <%= render 'form' %></div>
	      <div class="col-md-4 col-xs-4"></div>
		</div>
		<div class="row">
		<br/>
			<div class="col-md-4 col-xs-4"></div>
			<div class="col-md-3 col-xs-3"><%= link_to 'Back', roles_masters_path %></div>
			<div class="col-md-4 col-xs-4"></div>
		</div>
  	</div>
</body>
<br/>
<br/>
<br/>
</html>

app/views/roles_masters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Role name:</strong>
  <%= @roles_master.role_name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @roles_master.description %>
</p>

<p>
  <strong>Status:</strong>
  <%= @roles_master.status %>
</p>

<%= link_to 'Edit', edit_roles_master_path(@roles_master) %> |
<%= link_to 'Back', roles_masters_path %>