config/routes.rb
Rails.application.routes.draw do
  resources :emp_leave_masters
  resources :emp_requests
  resources :emp_masters
  resources :health_masters
  resources :emp_healths
  resources :roles_masters
  resources :leave_types
  resources :roles_masters
  resources :leave_types 
  devise_for :users
  get 'home/index'

  
   root 'home#index'

 devise_scope :user do 
     get '/users/sign_up' => 'users#sign_in'
  end

  get '/users' => 'users#index'

  get '/users/new' => 'users#new', :as => 'new_user'
  get '/users/:id/edit' => 'users#edit', :as => 'user_edit'
  get '/users/:id' => 'users#show', :as => 'user'
  patch '/users/:id' => 'users#update', :as => 'update_user'

  get '/users/create' => 'users#create', as: :create_user
  post 'create_users' => 'users#create', as: :create_users

end

app/models/emp_health.rb
class EmpHealth < ActiveRecord::Base
end

app/controllers/emp_healths_controller.rb
class EmpHealthsController < ApplicationController
  before_action :set_emp_health, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  
  # GET /emp_healths
  # GET /emp_healths.json
  def index
    @emp_healths = EmpHealth.all
  end

  # GET /emp_healths/1
  # GET /emp_healths/1.json
  def show
  end

  # GET /emp_healths/new
  def new
    @emp_health = EmpHealth.new
  end

  # GET /emp_healths/1/edit
  def edit
  end

  # POST /emp_healths
  # POST /emp_healths.json
  def create
    @emp_health = EmpHealth.new(emp_health_params)

    respond_to do |format|
      if @emp_health.save
        format.html { redirect_to @emp_health, notice: 'Emp health was successfully created.' }
        format.json { render :show, status: :created, location: @emp_health }
      else
        format.html { render :new }
        format.json { render json: @emp_health.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /emp_healths/1
  # PATCH/PUT /emp_healths/1.json
  def update
    respond_to do |format|
      if @emp_health.update(emp_health_params)
        format.html { redirect_to @emp_health, notice: 'Emp health was successfully updated.' }
        format.json { render :show, status: :ok, location: @emp_health }
      else
        format.html { render :edit }
        format.json { render json: @emp_health.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /emp_healths/1
  # DELETE /emp_healths/1.json
  def destroy
    @emp_health.destroy
    respond_to do |format|
      format.html { redirect_to emp_healths_url, notice: 'Emp health was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_emp_health
      @emp_health = EmpHealth.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def emp_health_params
      params.require(:emp_health).permit(:emp_id, :health_master_id, :answer, :user_id)
    end
end

app/helpers/emp_healths_helper.rb
module EmpHealthsHelper
end

app/views/emp_healths/_form.html.erb
<%= simple_form_for @emp_health do |f| %>
  <%= f.error_notification %>

  <div class="form-group">
    <%= f.input :health_master_id,collection:["hosp","doc"] ,input_html:{class:"form-control"}%>
    <%= f.input :answer ,input_html:{class:"form-control"}%>
    <%= f.input :user_id , :as => :hidden ,input_html: {value: current_user.id},class:"form-control"%>
  </div>
  <div class="col-md-3">
    <%= f.button :submit,"Go" ,class:"btn btn-primary"%>
  </div>
<% end %>

app/views/emp_healths/edit.html.erb
<br/>
<br/>
<br/>
<body>
<h1>Editing Emp Health</h1>
<div class="container">
	   <div class="row">
	      <div class="col-md-4 col-xs-4"></div>
	      <div class="col-md-4 col-xs-4"> <%= render 'form' %></div>
	      <div class="col-md-4 col-xs-4"></div>
		</div>
		<div class="row">
		<br/>
			<div class="col-md-4 col-xs-4"></div>
			<div class="col-md-4 col-xs-4">
<%= link_to 'Show', @emp_health %> |
<%= link_to 'Back', emp_healths_path %></div>
			<div class="col-md-4 col-xs-4"></div>
		</div>
  	</div>
</body>
</html>

app/views/emp_healths/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Emp Healths</h1>

<table class="table">
  <thead>
    <tr>
    <div class="col-md-4 col-xs-4">
      </div>
      <div class="col-md-4 col-xs-4">
      <th>Health master</th></div>
      <div class="col-md-4 col-xs-4">
      <th>Answer</th></div>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @emp_healths.each do |emp_health| %>
      <tr>
        
        <td><%= emp_health.health_master_id %></td>
        <td><%= emp_health.answer %></td>
        <td><%= link_to 'Show', emp_health %></td>
        <td><%= link_to 'Edit', edit_emp_health_path(emp_health) %></td>
        <td><%= link_to 'Destroy', emp_health, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Emp health', new_emp_health_path %>

app/views/emp_healths/new.html.erb
<br/>
<br/>
<br/>
<body>
<h1>New Employee Health</h1>
	<div class="container">
	   <div class="row">
	      <div class="col-md-4 col-xs-4"></div>
	      <div class="col-md-4 col-xs-4"> <%= render 'form' %></div>
	      <div class="col-md-4 col-xs-4"></div>
		</div>
		<div class="row">
		<br/>
			<div class="col-md-4 col-xs-4"></div>
			<div class="col-md-3 col-xs-3"><%= link_to 'Back', emp_healths_path %></div>
			<div class="col-md-4 col-xs-4"></div>
		</div>
  	</div>
</body>
</html>

app/views/emp_healths/show.html.erb
<div class="container">
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
	<div class="row">
		<div class="col-md-4 col-xs-4"></div>
		<div class="col-md-4 col-xs-4">
		<p id="notice"><%= notice %></p>

		
		<p>
  			<strong>Health master:</strong>
  			<%= @emp_health.health_master_id %>
		</p>

		<p>
  			<strong>Answer:</strong>
  			<%= @emp_health.answer %>
		</p>
		</div>
		<div class="col-md-4 col-xs-4"></div>
	</div>
		<div class="col-md-4 col-xs-4"></div>
		<div class="col-md-4 col-xs-4">
			<%= link_to 'Edit', edit_emp_health_path(@emp_health) %> |
			<%= link_to 'Back', emp_healths_path %></div>
		<div class="col-md-4 col-xs-4"></div>
</div>