config/routes.rb
Rails.application.routes.draw do
  resources :emp_leave_masters
  resources :emp_requests
  resources :emp_masters
  resources :health_masters
  resources :emp_healths
  resources :roles_masters
  resources :leave_types
  resources :roles_masters
  resources :leave_types 
  devise_for :users
  get 'home/index'

  
   root 'home#index'

 devise_scope :user do 
     get '/users/sign_up' => 'users#sign_in'
  end

  get '/users' => 'users#index'

  get '/users/new' => 'users#new', :as => 'new_user'
  get '/users/:id/edit' => 'users#edit', :as => 'user_edit'
  get '/users/:id' => 'users#show', :as => 'user'
  patch '/users/:id' => 'users#update', :as => 'update_user'

  get '/users/create' => 'users#create', as: :create_user
  post 'create_users' => 'users#create', as: :create_users

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      puts "---------------- first -----"


      user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      elsif user.employee?
        can :manage,[EmpMaster]
      elsif user.user?
        puts "---------------- herh -----"
        can :manage, [EmpHealth, EmpMaster, EmpRequest]
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/emp_health.rb
class EmpHealth < ActiveRecord::Base
end

app/models/emp_leave.rb
class EmpLeave < ActiveRecord::Base
	belongs_to :leave_type, foreign_key: :leave_id, class_name: "LeaveType"
	belongs_to :emp_master, foreign_key: :emp_id, class_name: "EmpMaster"
	
end

app/models/emp_leave_master.rb
class EmpLeaveMaster < ActiveRecord::Base
	belongs_to :leave_type, foreign_key: :leave_id, class_name: "LeaveType"
	belongs_to :emp_master, foreign_key: :emp_id, class_name: "EmpMaster"

end

app/models/emp_master.rb
class EmpMaster < ActiveRecord::Base
	belongs_to :roles_master, foreign_key: :role_id, class_name: "RolesMaster"

	has_many :emp_leaves, foreign_key: :emp_id, class_name: "EmpLeave"
end

app/models/emp_request.rb
class EmpRequest < ActiveRecord::Base
	belongs_to :emp_leave, foreign_key: :emp_leave_master_id, class_name: "EmpLeave"
	
	#calculating for the end date of leave
	def self.cal_leave(start_date,leave_days)
		end_date = start_date + (leave_days - 1).days	
	end
end

app/models/health_master.rb
class HealthMaster < ActiveRecord::Base
end

app/models/leave_type.rb
class LeaveType < ActiveRecord::Base
	validates :leave_name, presence: {message: "Leave name cannot be blank"}
  validates :num_days, presence: {message: "Number days cannot be blank"}
  validates :gender, presence: {message: "Gender cannot be blank"}
  
end

app/models/roles_master.rb
class RolesMaster < ActiveRecord::Base
 validates :role_name, presence: {message: "Role name cannot be blank"}
 validates :description, presence: {message: "Description cannot be blank"}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

belongs_to :roles_masters, foreign_key: :role_id, class_name: "RolesMaster"

  validates :username, presence: {message: "Username cannot be blank"}
  validates :email, presence: {message: "Email cannot be blank"}
  validates :password, presence: {message: "Password cannot be blank"}
  validates :password_confirmation, presence: {message: "Password confirmation cannot be blank"}
  validates :role_id, presence: {message: "Role ID cannot be blank"}
 



  def admin?
    self.role_id == 3
  end

  def user?
    self.role_id == 4
  end

   def employee?
      EmpMaster.where(user_id: self.id)[0]
  end
end

app/models/users.rb
class Users < ActiveRecord::Base  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  

  def index	
  	#check if exists 
  	#then redirect
  	unless EmpMaster.where(user_id: current_user.id)[0] 
	    redirect_to new_emp_master_path
	end
  end

 #  def emp_redirect
	#   	unless EmpMaster.where(user_id: current_user.id)[0] 
	#     redirect_to new_emp_master_path
 #  		end
	# end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
load_and_authorize_resource
 
  # GET /users
  # GET /users.json
  def index
    @user = User.new
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
    @users = RolesMaster.all
  end

  # GET /users/1/edit
  def edit
    @users = RolesMaster.all
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @users = RolesMaster.all

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Users was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    @users = RolesMaster.all
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'Users was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Users was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
     params.require(:user).permit(:username, :email, :password, :password_confirmation,:user_type_id , :entity_type_id,:entity_master_id,:status,:user_id ,:creator_id, :role_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/emp_healths_helper.rb
module EmpHealthsHelper
end

app/helpers/emp_leave_masters_helper.rb
module EmpLeaveMastersHelper
end

app/helpers/emp_leaves_helper.rb
module EmpLeavesHelper
end

app/helpers/emp_masters_helper.rb
module EmpMastersHelper
end

app/helpers/emp_requests_helper.rb
module EmpRequestsHelper
end

app/helpers/health_masters_helper.rb
module HealthMastersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/leave_types_helper.rb
module LeaveTypesHelper
end

app/helpers/roles_masters_helper.rb
module RolesMastersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit_form.html.erb
<%= simple_form_for @user, url: update_user_path do |f| %>
  <%= f.error_notification %>

 <div class="form-inputs">
          <%= f.input :username, required: true, autofocus: true %>
          <%= f.input :email, required: true, autofocus: true %>
          <%= f.input :password, required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length) %>
          <%= f.input :password_confirmation, required: true %>
          <%#= f.input :role_id, collection: @users,label_method: lambda {|bb| bb.role_name}, value_method: :id,class: "form-control"%>
          <%= f.association :roles_masters, collection: RolesMaster.all, label_method: :role_name, value_method: :id, include_blank: false, label: "Role:", style:"width:100%;", :input_html => {:class => 'form-control dropdown dropdown-toggle', style:"width:100%;float:center;"} %>
        </div>

  <div class="form-actions">
    <%= f.button :submit, "Submit" ,class:"btn btn-primary"%>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= simple_form_for @user, url: create_users_path do |f| %>
  <%= f.error_notification %>

<legend>New User Account</legend>
 <div class="container">
  
    <div class="form-horizontal">
      <div class="form-group">
        <div class="col-md-3">
          <%= f.input :username, required: true, autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-md-3">
          <%= f.input :email, required: true, autofocus: true %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-md-3">
          <%= f.input :password, required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length) %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-md-3">
          <%= f.input :password_confirmation, required: true %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-md-1">  
          <%= f.input :role_id, collection: @users,label_method: lambda {|bb| bb.role_name}, value_method: :id,class: "form-control"%>
        </div>
      </div>

      <div class="form-group">
        <div class="col-md-1">
          <%= f.button :submit, "Submit" ,class:"btn btn-primary"%>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<h3>Editing User</h3>
<div class="container">
	<div class="row">	
		<div class="col-md-4"></div>
		<div class="col-md-4">
		<%= render 'edit_form' %>

		<%= link_to 'Show', @user %> |
		<%= link_to 'Back', users_path %>
		</div>
		<div class="col-md-4"></div>
	</div>	
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table class="table">
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Created By</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', user_edit_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Users', new_user_path %>

app/views/users/new.html.erb
<div class="container">
	<div class="row">	
		<div class="col-md-4"></div>
		<div class="col-md-4">
		<%= render 'form' %>
		<%= link_to 'Back', users_path %>
		</div>
		<div class="col-md-4"></div>
	</div>	
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Status:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', user_edit_path(@user) %> |
<%= link_to 'Back', users_path %>