config/routes.rb
Rails.application.routes.draw do
  resources :emp_leave_masters
  resources :emp_requests
  resources :emp_masters
  resources :health_masters
  resources :emp_healths
  resources :roles_masters
  resources :leave_types
  resources :roles_masters
  resources :leave_types 
  devise_for :users
  get 'home/index'

  
   root 'home#index'

 devise_scope :user do 
     get '/users/sign_up' => 'users#sign_in'
  end

  get '/users' => 'users#index'

  get '/users/new' => 'users#new', :as => 'new_user'
  get '/users/:id/edit' => 'users#edit', :as => 'user_edit'
  get '/users/:id' => 'users#show', :as => 'user'
  patch '/users/:id' => 'users#update', :as => 'update_user'

  get '/users/create' => 'users#create', as: :create_user
  post 'create_users' => 'users#create', as: :create_users

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      puts "---------------- first -----"


      user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      elsif user.employee?
        can :manage,[EmpMaster]
      elsif user.user?
        puts "---------------- herh -----"
        can :manage, [EmpHealth, EmpMaster, EmpRequest]
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/emp_health.rb
class EmpHealth < ActiveRecord::Base
end

app/models/emp_leave.rb
class EmpLeave < ActiveRecord::Base
	belongs_to :leave_type, foreign_key: :leave_id, class_name: "LeaveType"
	belongs_to :emp_master, foreign_key: :emp_id, class_name: "EmpMaster"
	
end

app/models/emp_leave_master.rb
class EmpLeaveMaster < ActiveRecord::Base
	belongs_to :leave_type, foreign_key: :leave_id, class_name: "LeaveType"
	belongs_to :emp_master, foreign_key: :emp_id, class_name: "EmpMaster"

end

app/models/emp_master.rb
class EmpMaster < ActiveRecord::Base
	belongs_to :roles_master, foreign_key: :role_id, class_name: "RolesMaster"

	has_many :emp_leaves, foreign_key: :emp_id, class_name: "EmpLeave"
end

app/models/emp_request.rb
class EmpRequest < ActiveRecord::Base
	belongs_to :emp_leave, foreign_key: :emp_leave_master_id, class_name: "EmpLeave"
	
	#calculating for the end date of leave
	def self.cal_leave(start_date,leave_days)
		end_date = start_date + (leave_days - 1).days	
	end
end

app/models/health_master.rb
class HealthMaster < ActiveRecord::Base
end

app/models/leave_type.rb
class LeaveType < ActiveRecord::Base
	validates :leave_name, presence: {message: "Leave name cannot be blank"}
  validates :num_days, presence: {message: "Number days cannot be blank"}
  validates :gender, presence: {message: "Gender cannot be blank"}
  
end

app/models/roles_master.rb
class RolesMaster < ActiveRecord::Base
 validates :role_name, presence: {message: "Role name cannot be blank"}
 validates :description, presence: {message: "Description cannot be blank"}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

belongs_to :roles_masters, foreign_key: :role_id, class_name: "RolesMaster"

  validates :username, presence: {message: "Username cannot be blank"}
  validates :email, presence: {message: "Email cannot be blank"}
  validates :password, presence: {message: "Password cannot be blank"}
  validates :password_confirmation, presence: {message: "Password confirmation cannot be blank"}
  validates :role_id, presence: {message: "Role ID cannot be blank"}
 



  def admin?
    self.role_id == 3
  end

  def user?
    self.role_id == 4
  end

   def employee?
      EmpMaster.where(user_id: self.id)[0]
  end
end

app/models/users.rb
class Users < ActiveRecord::Base  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  

  def index	
  	#check if exists 
  	#then redirect
  	unless EmpMaster.where(user_id: current_user.id)[0] 
	    redirect_to new_emp_master_path
	end
  end

 #  def emp_redirect
	#   	unless EmpMaster.where(user_id: current_user.id)[0] 
	#     redirect_to new_emp_master_path
 #  		end
	# end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/emp_healths_helper.rb
module EmpHealthsHelper
end

app/helpers/emp_leaves_helper.rb
module EmpLeavesHelper
end

app/helpers/emp_masters_helper.rb
module EmpMastersHelper
end

app/helpers/emp_requests_helper.rb
module EmpRequestsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/leave_types_helper.rb
module LeaveTypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_messages.html.erb
<%# flash.each do |name, msg| %>
  <%# if msg.is_a?(String) %>
    <%#= content_tag :div, msg, :class => "flash_#{name}" %>
  <%# end %>
<%# end %>


<% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" style="margin-left: 25%; width: 700px; ">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
    <% end %>
<% end %>

app/views/layouts/_navi_emp.html.erb
<%# add navigation links to this file %>

<li><%= link_to 'Home', root_path %></li>
<li class="dropdown">
 <!--  <a href="#" class="dropdown-toggle active" data-toggle="dropdown" role="button" aria-haspopup="true"
     aria-expanded="false">Transactions<span class="caret"></span></a>
  <ul class="dropdown-menu">
    <!--<li>-->
    <!--<%#= link_to "Mobile Money", mm_logs_path %>-->
    <!--</li>-->


    <!--     <li class="dropdown dropdown-submenu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Cardless ATM</a>
          <ul class="dropdown-menu">

            <li>
              <%#= link_to "Main Transactions" %>
            </li>

            <li>
              <%#= link_to "Expired Transactions" %>
            </li>
          </ul>
        </li>
  </ul>
</li> -->
<li class="dropdown">
  <a href="#" class="dropdown-toggle active" data-toggle="dropdown" role="button" aria-haspopup="true"
     aria-expanded="false">Forms<span class="caret"></span></a>
  <ul class="dropdown-menu">
    <li>
      <%= link_to "Employee Form",new_emp_master_path %>
    </li>
    
    <li>
      <%= link_to "Health Questionnaire",emp_healths_path %>
    </li>

    <li>
      <%= link_to "Employee Leave Request",emp_requests_path %>
    </li>
   
  </ul>
</li>

<!-- <li class="dropdown">
  <a href="#" class="dropdown-toggle active" data-toggle="dropdown" role="button" aria-haspopup="true"
     aria-expanded="false">Users<span class="caret"></span></a>
  <ul class="dropdown-menu">
    <li>
      <%#= link_to "Users",users_path %>
    </li>
  </ul>
</li>
 -->
<li class="dropdown">
  <a href="#" class="dropdown-toggle active" data-toggle="dropdown" role="button" aria-haspopup="true"
     aria-expanded="false">Account<span class="caret"></span></a>
  <ul class="dropdown-menu">
    <li>
      <%= link_to "Edit profile",edit_user_registration_path %>
    </li>

    <li>
      <%= link_to "Log out", destroy_user_session_path , :method=> 'delete' %>
    </li>

  </ul>
</li>


app/views/layouts/_navigation.html.erb
<div id="wrapper">
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">


    <div id="logo"> <%= link_to 'HR', root_path %></div>
    <!--<div><%#= image_tag '/images/premium.png'%></div>-->
      <ul class="nav navbar-nav navbar-right">


       <% if user_signed_in? %>

	       <% if current_user.admin?%>
  		      <%= render 'layouts/navigation_links' %>
	       <% elsif current_user.user?%>
  		      <%= render 'layouts/navi_emp'%>
  	    <% end %>
       <% end %>

</ul>
</div>
 </header>
</div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

<li><%= link_to 'Home', root_path %></li>
<li class="dropdown">
 <!--  <a href="#" class="dropdown-toggle active" data-toggle="dropdown" role="button" aria-haspopup="true"
     aria-expanded="false">Transactions<span class="caret"></span></a>
  <ul class="dropdown-menu">
    <!--<li>-->
    <!--<%#= link_to "Mobile Money", mm_logs_path %>-->
    <!--</li>-->


    <!--     <li class="dropdown dropdown-submenu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Cardless ATM</a>
          <ul class="dropdown-menu">

            <li>
              <%#= link_to "Main Transactions" %>
            </li>

            <li>
              <%#= link_to "Expired Transactions" %>
            </li>
          </ul>
        </li>
  </ul>
</li> -->
<li class="dropdown">
  <a href="#" class="dropdown-toggle active" data-toggle="dropdown" role="button" aria-haspopup="true"
     aria-expanded="false">Set Ups<span class="caret"></span></a>
  <ul class="dropdown-menu">
    <li>
      <%= link_to "Roles",roles_masters_path %>
    </li>

     <li>
      <%= link_to "Employee Form",emp_masters_path %>
    </li>
    
    <li>
      <%= link_to "Emp Leaves",emp_leave_masters_path %>
    </li>

    <li>
      <%= link_to "Leave Types",leave_types_path %>
    </li>
    <li>
      <%= link_to "Health Questionnaire",health_masters_path %>
    </li>

    <li>
      <%= link_to "Employee Leave Request",emp_requests_path %>
    </li>
   
  </ul>
</li>

<li class="dropdown">
  <a href="#" class="dropdown-toggle active" data-toggle="dropdown" role="button" aria-haspopup="true"
     aria-expanded="false">Users<span class="caret"></span></a>
  <ul class="dropdown-menu">
    <li>
      <%= link_to "Users",users_path %>
    </li>
  </ul>
</li>

<li class="dropdown">
  <a href="#" class="dropdown-toggle active" data-toggle="dropdown" role="button" aria-haspopup="true"
     aria-expanded="false">Account<span class="caret"></span></a>
  <ul class="dropdown-menu">
    <li>
      <%= link_to "Edit profile",edit_user_registration_path %>
    </li>

    <li>
      <%= link_to "Log out", destroy_user_session_path , :method=> 'delete' %>
    </li>

  </ul>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HR</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  
  


  <%= render 'layouts/navigation'%>

</head>
<br/>
<br/>
<br/>
<body>
	<div class="container">
  <%= render 'layouts/messages'%>
		<%= yield %>
  	</div>
</body>
</html>